modLoader="javafml"
loaderVersion="[42,)"
license="MIT License"
issueTrackerURL="https://github.com/LegoMaster3650/Inventory-Crafter/issues"

[[mods]]
modId="inventory_crafter"
version="${file.jarVersion}"
displayName="Inventory Crafter"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/inventory-crafter"
logoFile="inventory_crafter.png"
credits="Charm Mod (original button concept)"
authors="LegoMaster3650"
description='''
Gives you a portable crafting table button/keybind if you have a crafting table item
'''

[[dependencies.inventory_crafter]]
	modId="forge"
	mandatory=true
	versionRange="[42.1,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.inventory_crafter]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.2,1.20)"
	ordering="NONE"
	side="BOTH"

[modproperties.inventory_crafter]
	catalogueItemIcon="minecraft:crafting_table"